### ISSUE TITLE
问题反馈专用issues（配图！！！！！！！）

### ISSUE THREAD

**Issue by Bill50han** [Billraozihan/MPG-Z390-GAMING-EDGE-AC-EFI#1]
rt

**Comment by 31869590** [comment]
请教下您说的“此efi的1.3，1.4版本使用了官方加密，请使用镜像自带EFI安装系统，并在安装好系统后再配置使用此EFI，并参照此教程重新加密引导。加密所需文件见此（下载后解压出的Utilities文件夹，加密请在macOS下进行）”这一段可以详细说下吗？您给的那个教程是英文的，也太长了，翻译的有点看不懂，新人希望指导下

**Comment by 31869590** [comment]
我的主板和cpu都跟您的一样，就是那段有点专业，不太明白了

**Comment by Bill50han** [comment]
> 请教下您说的“此efi的1.3，1.4版本使用了官方加密，请使用镜像自带EFI安装系统，并在安装好系统后再配置使用此EFI，并参照此教程重新加密引导。加密所需文件见此（下载后解压出的Utilities文件夹，加密请在macOS下进行）”这一段可以详细说下吗？您给的那个教程是英文的，也太长了，翻译的有点看不懂，新人希望指导下

这个加密其实就是oc在开机时会检测kext，dsdt等文件与加密时的内容是否一致，一致了才会开机。
这个功能其实没啥用，所有我以后的更新都会去掉这个功能。如果你需要的话，将Utilities这个文件夹移动到EFI分区根目录，并在mac下运行Utilities\CreateVault\create_vault.sh就可以了。注意加密后oc目录下的内容就一点都不能改变了，否则过不了开机检测。
