### ISSUE TITLE
z390i-gaming-edge-ac 能用吗

### ISSUE THREAD

**Issue by dev-wwj** [Billraozihan/MPG-Z390-GAMING-EDGE-AC-EFI#2]
z390i-gaming-edge-ac能用吗

**Comment by Bill50han** [comment]
应该可以。显卡方面我是使用了z390m-gaming-edge-ac的配置，可以正常用。所以我猜测这三款主板差别不大。别的硬件差不多的应该可以通用。你的电脑如果有独显，按照readme里的步骤去除-wegnoegpu就行。如果你换了博通的网卡，那么可能需要添加博通的kext并删除以intelbluetooth开头的两个kext。

**Comment by Bill50han** [comment]
抱歉我刚查了一下你这块主板的参数，网卡和声卡都和我的不同。那么你需要删除刚刚我提到的以intelbluetooth开头的两个kext和IntelMausi.kext。添加RealtekRTL8111.kext。声卡方面可能需要参照xjn的博客（https://blog.xjn819.com/?p=543 ）的2.3.1章节重新设置id。

**Comment by Billraozihan** [comment]
xjn的博客：https://blog.xjn819.com/?p=543

**Comment by Bill50han** [comment]
opencore和clover的kext/efi驱动加载方法不同，建议你读一遍xjn博客的第2大章

**Comment by xiaoyigg** [comment]
> opencore和clover的kext/efi驱动加载方法不同，建议你读一遍xjn博客的第2大章

你好，请问z390 gaming carbon 能直接用吗 9700kf+vega56

**Comment by Bill50han** [comment]
> opencore和clover的kext/efi驱动加载方法不同，建议你读一遍xjn博客的第2大章
> 
> 你好，请问z390 gaming carbon 能直接用吗 9700kf+vega56

直接用肯定不行，你至少需要将-wegnoegpu删去，核显id改为加速专用的id。你的音频输出id和我的也可能不一样。我不太清楚vega56用不用驱动，如果用的话你还需要加上驱动。

**Comment by xiaoyigg** [comment]
> > opencore和clover的kext/efi驱动加载方法不同，建议你读一遍xjn博客的第2大章
> > 你好，请问z390 gaming carbon 能直接用吗 9700kf+vega56
> 
> 直接用肯定不行，你至少需要将-wegnoegpu删去，核显id改为加速专用的id。你的音频输出id和我的也可能不一样。我不太清楚vega56用不用驱动，如果用的话你还需要加上驱动。

我能QQ联系你吗···

**Comment by xiaoyigg** [comment]
对了，我的z390 gaming carbon里没有关闭csm选项，请问是在哪里关闭啊？
我在网上搜索说微星的主板开启安全启动就是关闭csm，一头雾水。

**Comment by Bill50han** [comment]
> 对了，我的z390 gaming carbon里没有关闭csm选项，请问是在哪里关闭啊？
> 我在网上搜索说微星的主板开启安全启动就是关闭csm，一头雾水。

f7高级模式-settings-高级-Windows操作系统的配置-Windows 10 WHQL支持 选择允许就等于关闭csm

**Comment by dev-wwj** [comment]
> 抱歉我刚查了一下你这块主板的参数，网卡和声卡都和我的不同。那么你需要删除刚刚我提到的以intelbluetooth开头的两个kext和IntelMausi.kext。添加RealtekRTL8111.kext。声卡方面可能需要参照xjn的博客（https://blog.xjn819.com/?p=543 ）的2.3.1章节重新设置id。
